### ISSUE TITLE
Strange banding on Chapter 04 deferred rendering

### ISSUE THREAD

**Issue by HugoOsornio** [PacktPublishing/The-Modern-Vulkan-Cookbook#10]
![ModernVulkan_Chapter04](https://github.com/PacktPublishing/The-Modern-Vulkan-Cookbook/assets/25018996/7262288b-4dec-43c3-a8ac-ebbad7aea578)

Hello folks, I'm noticing some banding in the textures in chapter 4, attaching a screenshot, is this expected?

**Comment by preetishkakkar** [comment]
These are artifacts that happen with basic shadow map technique due to limited resolution, the solution is to implement techniques like cascade shadow maps, but for the book, we decided to go with simpler one since we wanted to focus more on Vulkan, I might implement CSM (or something similar) in future. Please feel free to close this issue if this answer is sufficient or ask queries if you have.

**Comment by HugoOsornio** [comment]
Thanks for the explanation, got it.
